### ISSUE TITLE
Target class [Tymon\JWTAuth\Middleware\GetUserFromToken] does not exist.

### ISSUE THREAD

**Issue by baradhili** [Tony133/laravel-api-boilerplate-jwt#13]
Hitting this when running scribe over the api... 
I don't think its scribe since that looks internally.. trying to find the GetUserFromToken method in the code seems to come up blank

> "require": {
>         "php": "^7.3",
>         "fideloper/proxy": "^4.2",
>         "fruitcake/laravel-cors": "^2.0",
>         "guzzlehttp/guzzle": "^7.0.1",
>         "laravel/framework": "^8.0",
>         "laravel/tinker": "^2.0",
>         "tymon/jwt-auth": "^1.0"
>     },
>     "require-dev": {
>         "facade/ignition": "^2.3.6",
>         "fzaninotto/faker": "^1.9.1",
>         "knuckleswtf/scribe": "^2.5",
>         "mockery/mockery": "^1.3.1",
>         "nunomaduro/collision": "^5.0",
>         "phpunit/phpunit": "^9.3"
>     },

**Comment by Tony133** [comment]
I am currently unable to reproduce the problem.
