### ISSUE TITLE
Refresh token not working + Login not working "When try to logout first and then login"

### ISSUE THREAD

**Issue by Mohanraj153** [Tony133/laravel-api-boilerplate-jwt#14]
Hi,
I have tried "http://127.0.0.1:8000/api/auth/refresh?token=[:token]"
but it's shows some error like below,
==============================
{
    "message": "Method App\\Http\\Controllers\\Api\\Auth\\RefreshTokenController::json does not exist.",
    "exception": "BadMethodCallException",
    "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
    "line": 68,
    "trace": [
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\app\\Http\\Controllers\\Api\\Auth\\RefreshTokenController.php",
            "line": 25,
            "function": "__call",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
            "line": 54,
            "function": "get",
            "class": "App\\Http\\Controllers\\Api\\Auth\\RefreshTokenController",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 254,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 197,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 693,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\tymon\\jwt-auth\\src\\Http\\Middleware\\RefreshToken.php",
            "line": 40,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Tymon\\JWTAuth\\Http\\Middleware\\RefreshToken",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\tymon\\jwt-auth\\src\\Http\\Middleware\\Authenticate.php",
            "line": 32,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Tymon\\JWTAuth\\Http\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php",
            "line": 127,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php",
            "line": 63,
            "function": "handleRequest",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 695,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 670,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 636,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 625,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 166,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php",
            "line": 86,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 141,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 110,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\public\\index.php",
            "line": 52,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "D:\\xampp\\htdocs\\NewProject\\laravel-api\\server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}

**Comment by Tony133** [comment]
the problem is this:`JWT_BLACKLIST_ENABLED = true` in .env

if it is `true` the update token does not work but the logout does

you have to put it on `false`

**Comment by Mohanraj153** [comment]
> the problem is this:`JWT_BLACKLIST_ENABLED = true` in .env
> 
> if it is `true` the update token does not work but the logout does
> 
> you have to put it on `false`
> 

Yes, i put it in .env. But it's not working.

**Comment by Tony133** [comment]
it works for me but it all depends on this: `JWT_BLACKLIST_ENABLED = true` in .env

see screenshot

in my opinion

<img width="1355" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/106358315-e0120700-630b-11eb-82b8-9385daa051bb.png">

**Comment by Mohanraj153** [comment]
Either put in TRUE or false. It's not working. Can you give any alternative solution? (or) can I give my source to you?

**Comment by Tony133** [comment]
At the moment I don't have a solution as I don't have much time, if you have one, you are free to do a pull for it.

**Comment by Mohanraj153** [comment]
> At the moment I don't have a solution as I don't have much time, if you have one, you are free to do a pull for it. 

Nice reply.

**Comment by Tony133** [comment]
I give you the solution, unfortunately it doesn't work for you at the moment nothing comes to mind, as I told you if you have one let me know?
