### ISSUE TITLE
Login not working "When try to logout first and then login"

### ISSUE THREAD

**Issue by Mohanraj153** [Tony133/laravel-api-boilerplate-jwt#15]
Hi,
it's fine when try first login api. after finished my logout process then try to relogging process in ERROR.
Below Error Response :
===============
{
    "error": "Unauthorized",
    "message": "User not found"
}

**Comment by Tony133** [comment]
you did `php artisan jwt: secret`

**Comment by Mohanraj153** [comment]
No, I'm not did. what to do?

**Comment by Mohanraj153** [comment]
Yes, I did but still not working

**Comment by Tony133** [comment]
`php artisan jwt: secret` not working?

**Comment by Mohanraj153** [comment]
I have check that API after run the commant & set the secret key .env. Have you any solution or not?

**Comment by Tony133** [comment]
it works for me but it all depends on this: `JWT_BLACKLIST_ENABLED = true` in .env, in my opinion

see screenshot

<img width="1355" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/106358315-e0120700-630b-11eb-82b8-9385daa051bb.png">


``

**Comment by Mohanraj153** [comment]
> it works for me but it all depends on this: `JWT_BLACKLIST_ENABLED = true` in .env, in my opinion
> 
> see screenshot
> 
> <img width="1355" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/106358315-e0120700-630b-11eb-82b8-9385daa051bb.png">
> 
> 

It's not worked for me. I think you are giving wrong source to commit or else you can't fix the bug. Anyway give the solution for this error.

**Comment by Mohanraj153** [comment]
Can you give any alternative solution? (or) can I give my source to you?

**Comment by Tony133** [comment]
At the moment I don't have a solution as I don't have much time, if you have one, you are free to do a pull for it. Anyway try to re-download the repository and do the passages that are in the readme again.

**Comment by Mohanraj153** [comment]
Nice reply. No one can download this sources because it's totally time waste.

 Note For Developer : 
That repository author has never, ever support to developers.
